//
//  LMTangramElementFactoryProtocol.h
//  MyTangram
//
//  Created by tongleiming on 2019/3/25.
//  Copyright © 2019年 Hello World Corporation. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "LMTangramItemModelProtocol.h"

NS_ASSUME_NONNULL_BEGIN

@protocol LMTangramElementFactoryProtocol <NSObject>

@required

/**
 Return view by model
 
 @param model ItemModel Generated by ItemModelFactoty
 @return view
 */
+ (UIView *)elementByModel:(NSObject<LMTangramItemModelProtocol> *)model;

/**
 Return view after be refreshed
 
 @param  element to be refreshed
 @return element after refreshed
 */
+ (UIView *)refreshElement:(UIView *)element byModel:(NSObject<LMTangramItemModelProtocol> *)model;


@end

NS_ASSUME_NONNULL_END
